### ISSUE TITLE
Errors on clicking "Use Map"

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightMaps#18]
In the latest versions of all packages (listed below).

Also attached some warnings which may or may not be new.

```r
Error in summarise_impl(.data, dots) : 
  Column `NAME_CIA` can't be modified because it's a grouping variable
In addition: Warning messages:
1: In st_centroid.sf(mapdata) :
  st_centroid assumes attributes are constant over geometries of x
2: In st_centroid.sfc(st_geometry(x), of_largest_polygon = of_largest_polygon) :
  st_centroid does not give correct centroids for longitude/latitude data
3: In st_simplify.sfc(st_geometry(x), preserveTopology, dTolerance) :
  st_simplify does not correctly simplify longitude/latitude data, dTolerance needs to be in decimal degrees
```

<details>

<summary>Package versions</summary>

```r
> sessionInfo()
[...]
other attached packages:
[1] iNZightMaps_2.0-0      sf_0.6-3               iNZight_3.2.2         
[4] cairoDevice_2.25       gWidgets2_1.0-7        digest_0.6.15         
[7] RGtk2_2.20.35          objectProperties_0.6.5 objectSignals_0.10.2  

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.4     purrr_0.2.5          reshape2_1.4.3      
 [4] splines_3.5.0        lattice_0.20-35      gWidgets2RGtk2_1.0-7
 [7] colorspace_1.3-2     viridisLite_0.3.0    survival_2.42-6     
[10] rlang_0.2.1          e1071_1.7-0          hexbin_1.27.2       
[13] pillar_1.3.0         foreign_0.8-71       glue_1.3.0          
[16] DBI_1.0.0            sp_1.3-1             RColorBrewer_1.1-2  
[19] bindrcpp_0.2.2       plyr_1.8.4           bindr_0.1.1         
[22] stringr_1.3.1        MatrixModels_0.4-1   RgoogleMaps_1.4.2   
[25] memoise_1.1.0        SparseM_1.77         iNZightTools_1.5.3  
[28] maptools_0.9-3       quantreg_5.36        class_7.3-14        
[31] Rcpp_0.12.18         classInt_0.2-3       iNZightPlots_2.7.8  
[34] countrycode_1.00.0   png_0.1-7            stringi_1.2.4       
[37] dplyr_0.7.6          iNZightMR_2.2-3      survey_3.33-2       
[40] grid_3.5.0           tools_3.5.0          magrittr_1.5        
[43] tibble_1.4.2         dichromat_2.0-0      crayon_1.3.4        
[46] pkgconfig_2.0.1      Matrix_1.2-14        spData_0.2.9.3      
[49] assertthat_0.2.0     R6_2.2.2             boot_1.3-20         
[52] units_0.6-0          compiler_3.5.0   
```

</details>

<details>
<summary>Traceback</summary>

```r
> traceback()
23: stop(list(message = "Column `NAME_CIA` can't be modified because it's a grouping variable", 
        call = summarise_impl(.data, dots), cppstack = list(file = "", 
            line = -1L, stack = c("/home/tell029/R-3.5.0/library/dplyr/libs/dplyr.so(Rcpp::exception::exception(char const*, bool)+0x82) [0x7f5de1a9d402]", 
            "/home/tell029/R-3.5.0/library/dplyr/libs/dplyr.so(Rcpp::stop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x27) [0x7f5de1a9d537]", 
            "/home/tell029/R-3.5.0/library/dplyr/libs/dplyr.so(void dplyr::bad_col<char const*>(dplyr::SymbolString const&, char const*)+0x1f9) [0x7f5de1ab4e59]", 
            "/home/tell029/R-3.5.0/library/dplyr/libs/dplyr.so(check_not_groups(dplyr::QuosureList const&, dplyr::GroupedDataFrame const&)+0x53e) [0x7f5de1b748de]", 
            "/home/tell029/R-3.5.0/library/dplyr/libs/dplyr.so(Rcpp::DataFrame_Impl<Rcpp::PreserveStorage> summarise_grouped<dplyr::GroupedDataFrame, dplyr::LazySplitSubsets<dplyr::GroupedDataFrame> >(Rcpp::DataFrame_Impl<Rcpp::PreserveStorage> const&, dplyr::QuosureList const&)+0xa0) [0x7f5de1b966e0]", 
            "/home/tell029/R-3.5.0/library/dplyr/libs/dplyr.so(summarise_impl(Rcpp::DataFrame_Impl<Rcpp::PreserveStorage>, dplyr::QuosureList)+0x19b) [0x7f5de1b91a0b]", 
            "/home/tell029/R-3.5.0/library/dplyr/libs/dplyr.so(_dplyr_summarise_impl+0x5e) [0x7f5de1a9c8ce]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4d0613]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x516fe9]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x513d35]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4ca2f4]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x515ad8]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x515f09]", "/home/tell029/R-3.5.0/bin/exec/R() [0x516231]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4ca2f4]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4d9feb]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x713) [0x4d9d83]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4df137]", "/home/tell029/R-3.5.0/bin/exec/R() [0x513d35]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4ca2f4]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4deb2f]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d006a]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4d9feb]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x713) [0x4d9d83]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4df137]", "/home/tell029/R-3.5.0/bin/exec/R() [0x513d35]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4ca2f4]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R() [0x4d2437]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4dd914]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4dc7b5]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4dc7b5]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4dc7b5]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(R_forceAndCall+0x146) [0x4dde36]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x42a89d]", "/home/tell029/R-3.5.0/bin/exec/R() [0x513d35]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4ca2f4]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x330) [0x4d99a0]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4dd914]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4dc7b5]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4db103]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x2e2) [0x4d9952]", 
            "/home/tell029/R-3.5.0/bin/exec/R() [0x4dc7b5]", "/home/tell029/R-3.5.0/bin/exec/R(Rf_eval+0x4e8) [0x4d9b58]"
            ))))
22: summarise_impl(.data, dots)
21: summarise.tbl_df(.tbl, !!!funs)
20: NextMethod()
19: summarise.sf(.tbl, !!!funs)
18: summarise(.tbl, !!!funs)
17: dplyr::summarise_at(., dplyr::vars(-dplyr::matches("^geometry$")), 
        dplyr::last)
16: function_list[[k]](value)
15: withVisible(function_list[[k]](value))
14: freduce(value, `_function_list`)
13: `_fseq`(`_lhs`)
12: eval(quote(`_fseq`(`_lhs`)), env, env)
11: eval(quote(`_fseq`(`_lhs`)), env, env)
10: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
9: mapdata %>% dplyr::group_by(UQ((as.name(by.map)))) %>% dplyr::summarise_at(dplyr::vars(-dplyr::matches("^geometry$")), 
       dplyr::last)
8: iNZightMapPlotRegion(data, map, ...)
7: iNZightMaps::iNZightMapPlot(data = activeData, map = mapData, 
       type = "region", by.data = data.var, by.map = map.var, simplification.level = 0.01, 
       multiple.summaryobs = has.multipleobs, sequence.var = sequence.var)
6: o(h, ...)
5: o$update(...)
4: FUN(X[[i]], ...)
3: lapply(..observers[[signal]], function(o) {
       ind <- lapply(..blocked_observers[[signal]], function(i) identical(i, 
           o))
       if (!any(unlist(ind))) 
           o$update(...)
   })
2: self$notify_observers(signal = signal, ...)
1: (function (self, ...) 
   {
       self$notify_observers(signal = signal, ...)
   })(new("GButton", .xData = <environment>), <pointer: 0x1b8b0920>)
```

</details>

**Comment by daniel-barnett** [comment]
I think this is something to do with dplyr which had to be fixed earlier. I'll give it a check over this afternoon

**Comment by daniel-barnett** [comment]
Does the latest version, https://github.com/iNZightVIT/iNZightMaps/commit/67adfa122d2e478eaff28d8bf2aa0ce67cabcdc3, work?

**Comment by tmelliott** [comment]
I don't believe so.

**Comment by daniel-barnett** [comment]
That is the latest update from about 20 mins ago when I merged support-3.2 into dev (support-3.2 had the fix from a while ago)

**Comment by tmelliott** [comment]
Yah I'd just pulled and tried but still get the same problem.

**Comment by daniel-barnett** [comment]
Does it work now? If not, can you attach the traceback if possible? 

It's working OK on mine with updated dplyr, etc.

**Comment by tmelliott** [comment]
Seems to work now - not sure if recent commit or if I was having caching problems 'cause of an open R I had forgotten about.
